### ISSUE TITLE
Nama Kota tidak Ada Pilihan

### ISSUE THREAD

**Issue by DadanDarmawan** [eezhal92/myongkir#13]
Selamat Pagi,, saya sudah instal pluginnya, tapi setelah isi Provinsi, di Kota nya hanya muncul satu kota saja, Ibu Kota provinsinya saja

**Comment by eezhal92** [comment]
sorry baru response, kyknya dekat-dekat ini saya coba u/ ngoprek2 repo ini. bisa spesifikasikan versi wordpress dan woocommerce yg digunakan?

**Comment by DadanDarmawan** [comment]
Trims sudah respon balik. Saya pake WP Versi 4.8.2  Woo Comerce Versi 3.2.1

**Comment by eezhal92** [comment]
updated, silakan di coba lagi :)

**Comment by DadanDarmawan** [comment]
oke Trims
