### ISSUE TITLE
Tidak bisa jalan di woocomerce terbaru Version 2.6.4 

### ISSUE THREAD

**Issue by tahanprahara** [eezhal92/myongkir#5]
setelah plugin di aktifkan maka page shop dan woocommer setting tidak bisa di buka...

Page Chart juga tidak bisa di buka

smoga ada update tutorial dan pemasangan sehingga bisa digunakan kembali

**Comment by fujianto** [comment]
Barusan dicoba di versi 2.6.4 di localhost wamp, fungsin berjalan dengan semestinya.
Mungkin ada masalah di API rajaongkir nya?
