### ISSUE TITLE
rajaongkir pro version

### ISSUE THREAD

**Issue by frezendisney** [eezhal92/myongkir#6]
pak mau tanya punya rajaongkir plugin woocommerce untuk yg pro paid. agar kecamantannya juga bisa muncul pak. ? aplikasi bpk sangat membantu sekali. terima kasih

**Comment by fujianto** [comment]
Mungkin harus pakai api rajaongkir yg pro?
Kalau kecamatan berpengaruh juga dengan harga ongkir? Kalau tidak mungkin lebih bagus kalau kecamatannya ditulis manual.

**Comment by eezhal92** [comment]
saat ini blm support u/ versi pro :)
