### ISSUE TITLE
error myongkir-shipping.php line 188

### ISSUE THREAD

**Issue by ghost** [eezhal92/myongkir#7]
selamat malam, saya sudah coba install plugins nya, tetapi sering muncul
 Warning: Invalid argument supplied for foreach() in ...\myongkir-shipping.php on line 188

**Comment by fujianto** [comment]
Api rajaongkir nya sudah dimasukkan dengan benar?

**Comment by widyjantiko** [comment]
saya sudah tapi masih keluar Warning: Invalid argument supplied for foreach() in myongkir-shipping.php on line 188

**Comment by ayumahreza** [comment]
Hai, tadi saya juga error, tapi sudah bisa. Coba tambahkan ini if (is_array($courier) || is_object($courier)) :

                        if (is_array($courier) || is_object($courier))
				{
					foreach ( $courier['costs'] as $item ) {
						foreach ( $item['cost'] as $cost ) {
							$this->add_rate(
								array(
									'id' => $this->id . "_" . $courier['name'] . "_" . $item['service'] ,
									'label' => $courier['name'] . " " . $item['service'],
									'cost' => $cost['value'],
									'calc_tax' => 'per_item'
								)
							);
						}
					}
				}	
	
Btw, terimakasih terimakasih terimakasih banyak ya eezhal92 untuk add-on nya! :)

**Comment by eezhal92** [comment]
sepertinya sdh solved, tolong readme nya dibaca lagi :)
