### ISSUE TITLE
Support alamat internasional

### ISSUE THREAD

**Issue by ekafyi** [eezhal92/myongkir#8]
Apakah plugin ini mendukung cek tarif pengiriman internasional (untuk paket Basic)?

Terima kasih.

**Comment by fujianto** [comment]
Sepertinya hanya untuk daerah lokal saja. Cek rajaongkir.com untuk lengkapnya.

**Comment by ekafyi** [comment]
API Rajaongkir.com-nya sudah support untuk cek tarif internasional (saya sudah cek lewat cURL juga, berhasil). http://rajaongkir.com/dokumentasi/basic

Tapi di website Woocommerce saya yang menggunakan plugin Myongkir, kalau saya masukkan alamat internasional, ongkirnya tidak muncul ("No shipping methods available..."). Karena itu saya tanya, apa memang plugin Myongkir-nya tidak support atau mungkin ada error di hal lainnya.

**Comment by eezhal92** [comment]
saat ini blm support mas :)
