### ISSUE TITLE
Tidak jalan di Woocomerce Version 2.6.8

### ISSUE THREAD

**Issue by widyjantiko** [eezhal92/myongkir#9]
Propinsi keluar, tapi kota tidak keluar

**Comment by wansoleh** [comment]
saya coba woocommerceny diturunkan ke 2.6.14 pluginnya dinonaktifkan/dihapus, dan tabel woocommerce sebelumnya harus dihapus manual dulu di phpmyadmin. masalahnya produk lama tidak nampak di menu shop, tapi tinggal dihapus aja di add produk yang baru. insya Allah sy coba berhasil.

**Comment by eezhal92** [comment]
readme tolong di baca, sdh di-update :)
